"""The curated recipe set: thirty classics, hand-entered."""

RECIPES = [
    {
        "id": "negroni",
        "name": "Negroni",
        "glass": "rocks",
        "method": "stirred",
        "garnish": "orange peel",
        "instructions": "Stir with ice, strain over a large cube, express an orange peel over the top.",
        "steps": [
            "Add {gin} to a mixing glass.",
            "Add {campari}.",
            "Add {sweet-vermouth}.",
            "Fill the mixing glass with ice.",
            "Stir for about 20 seconds, until cold.",
            "Strain into a rocks glass over one large ice cube.",
            "Express an orange peel over the top and drop it in.",
        ],
        "ingredients": [
            ("gin", "1 oz", False),
            ("campari", "1 oz", False),
            ("sweet-vermouth", "1 oz", False),
        ],
    },
    {
        "id": "old-fashioned",
        "name": "Old Fashioned",
        "glass": "rocks",
        "method": "stirred",
        "garnish": "orange peel",
        "instructions": "Stir with ice until cold, strain over a large cube.",
        "steps": [
            "Add {rich-syrup} to a mixing glass.",
            "Add {aromatic-bitters}.",
            "Add {bourbon}.",
            "Fill the mixing glass with ice.",
            "Stir for about 30 seconds, until very cold.",
            "Strain into a rocks glass over one large ice cube.",
            "Express an orange peel over the top and drop it in.",
        ],
        "ingredients": [
            ("bourbon", "2 oz", False),
            ("rich-syrup", "1 tsp", False),
            ("aromatic-bitters", "2 dashes", False),
        ],
    },
    {
        "id": "manhattan",
        "name": "Manhattan",
        "glass": "coupe",
        "method": "stirred",
        "garnish": "brandied cherry",
        "instructions": "Stir with ice until well chilled, strain into a chilled coupe.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {rye-whiskey} to a mixing glass.",
            "Add {sweet-vermouth}.",
            "Add {aromatic-bitters}.",
            "Fill the mixing glass with ice.",
            "Stir for about 30 seconds, until very cold.",
            "Dump the ice water from the coupe.",
            "Strain into the chilled coupe.",
            "Garnish with a brandied cherry.",
        ],
        "ingredients": [
            ("rye-whiskey", "2 oz", False),
            ("sweet-vermouth", "1 oz", False),
            ("aromatic-bitters", "2 dashes", False),
        ],
    },
    {
        "id": "martini",
        "name": "Martini",
        "glass": "coupe",
        "method": "stirred",
        "garnish": "lemon twist or olive",
        "instructions": "Stir with ice for a good twenty seconds, strain into a chilled glass.",
        "steps": [
            "Chill a coupe or martini glass (fill it with ice water while you mix).",
            "Add {gin} to a mixing glass.",
            "Add {dry-vermouth}.",
            "Add {orange-bitters} (if using).",
            "Fill the mixing glass with ice.",
            "Stir for 20 to 30 seconds, until very cold.",
            "Dump the ice water from the glass.",
            "Strain into the chilled glass.",
            "Garnish with a lemon twist or an olive.",
        ],
        "ingredients": [
            ("gin", "2 1/2 oz", False),
            ("dry-vermouth", "1/2 oz", False),
            ("orange-bitters", "1 dash", True),
        ],
    },
    {
        "id": "daiquiri",
        "name": "Daiquiri",
        "glass": "coupe",
        "method": "shaken",
        "garnish": "lime wheel",
        "instructions": "Shake hard with ice, double-strain into a chilled coupe.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {white-rum} to a shaker.",
            "Add {lime-juice}.",
            "Add {simple-syrup}.",
            "Fill the shaker with ice.",
            "Shake hard for 10 to 12 seconds.",
            "Dump the ice water from the coupe.",
            "Double-strain (through a fine strainer too) into the chilled coupe.",
            "Garnish with a lime wheel.",
        ],
        "ingredients": [
            ("white-rum", "2 oz", False),
            ("lime-juice", "1 oz", False),
            ("simple-syrup", "3/4 oz", False),
        ],
    },
    {
        "id": "margarita",
        "name": "Margarita",
        "glass": "rocks",
        "method": "shaken",
        "garnish": "lime wedge, salt rim",
        "instructions": "Shake with ice, strain over fresh ice in a salt-rimmed glass.",
        "steps": [
            "Run a lime wedge around half the rim of a rocks glass and dip it in salt.",
            "Add {blanco-tequila} to a shaker.",
            "Add {triple-sec}.",
            "Add {lime-juice}.",
            "Fill the shaker with ice.",
            "Shake hard for 10 seconds.",
            "Fill the rocks glass with fresh ice.",
            "Strain the drink into the glass.",
            "Garnish with a lime wedge.",
        ],
        "ingredients": [
            ("blanco-tequila", "2 oz", False),
            ("triple-sec", "1 oz", False),
            ("lime-juice", "1 oz", False),
        ],
    },
    {
        "id": "whiskey-sour",
        "name": "Whiskey Sour",
        "glass": "rocks",
        "method": "shaken",
        "garnish": "lemon peel, cherry",
        "instructions": "Dry-shake if using egg white, then shake with ice and strain over fresh ice.",
        "steps": [
            "Add {bourbon} to a shaker.",
            "Add {lemon-juice}.",
            "Add {simple-syrup}.",
            "Add {egg-white} (if using).",
            "If you added egg white, shake without ice for 10 seconds to foam it.",
            "Fill the shaker with ice.",
            "Shake hard for 10 seconds.",
            "Fill a rocks glass with fresh ice.",
            "Strain the drink into the glass.",
            "Garnish with a lemon peel and a cherry.",
        ],
        "ingredients": [
            ("bourbon", "2 oz", False),
            ("lemon-juice", "1 oz", False),
            ("simple-syrup", "3/4 oz", False),
            ("egg-white", "1", True),
        ],
    },
    {
        "id": "mojito",
        "name": "Mojito",
        "glass": "collins",
        "method": "built",
        "garnish": "mint sprig",
        "instructions": "Gently press the mint with the syrup, add rum and lime, fill with crushed ice, top with soda.",
        "steps": [
            "Add {mint} to a collins glass.",
            "Add {simple-syrup}.",
            "Press the mint gently with a muddler (bruise it, don't shred it).",
            "Add {white-rum}.",
            "Add {lime-juice}.",
            "Fill the glass with crushed ice.",
            "Stir to mix.",
            "Top with {soda-water}.",
            "Garnish with a mint sprig (slap it first to wake it up).",
        ],
        "ingredients": [
            ("white-rum", "2 oz", False),
            ("lime-juice", "1 oz", False),
            ("simple-syrup", "3/4 oz", False),
            ("mint", "8 leaves", False),
            ("soda-water", "top", False),
        ],
    },
    {
        "id": "moscow-mule",
        "name": "Moscow Mule",
        "glass": "copper mug",
        "method": "built",
        "garnish": "lime wedge",
        "instructions": "Build over ice in a mug, stir once.",
        "steps": [
            "Fill a copper mug with ice.",
            "Add {vodka}.",
            "Add {lime-juice}.",
            "Top with {ginger-beer}.",
            "Stir once.",
            "Garnish with a lime wedge.",
        ],
        "ingredients": [
            ("vodka", "2 oz", False),
            ("lime-juice", "1/2 oz", False),
            ("ginger-beer", "top", False),
        ],
    },
    {
        "id": "dark-n-stormy",
        "name": "Dark 'n' Stormy",
        "glass": "collins",
        "method": "built",
        "garnish": "lime wedge",
        "instructions": "Build ginger beer over ice, float the dark rum on top.",
        "steps": [
            "Fill a collins glass with ice.",
            "Add {lime-juice}.",
            "Add {ginger-beer}.",
            "Slowly pour {dark-rum} over the back of a spoon so it floats on top.",
            "Garnish with a lime wedge.",
        ],
        "ingredients": [
            ("dark-rum", "2 oz", False),
            ("ginger-beer", "4 oz", False),
            ("lime-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "negroni-sbagliato",
        "name": "Negroni Sbagliato",
        "glass": "rocks",
        "method": "built",
        "garnish": "orange slice",
        "instructions": "Build over ice, add the prosecco last and stir gently once.",
        "steps": [
            "Fill a rocks glass with ice.",
            "Add {campari}.",
            "Add {sweet-vermouth}.",
            "Top with {prosecco}.",
            "Stir gently, once.",
            "Garnish with an orange slice.",
        ],
        "ingredients": [
            ("campari", "1 oz", False),
            ("sweet-vermouth", "1 oz", False),
            ("prosecco", "1 oz", False),
        ],
    },
    {
        "id": "aperol-spritz",
        "name": "Aperol Spritz",
        "glass": "wine glass",
        "method": "built",
        "garnish": "orange slice",
        "instructions": "Fill with ice, prosecco first, then Aperol, then a splash of soda.",
        "steps": [
            "Fill a wine glass with ice.",
            "Add {prosecco}.",
            "Add {aperol}.",
            "Add {soda-water}.",
            "Stir gently once.",
            "Garnish with an orange slice.",
        ],
        "ingredients": [
            ("aperol", "2 oz", False),
            ("prosecco", "3 oz", False),
            ("soda-water", "1 oz", False),
        ],
    },
    {
        "id": "americano",
        "name": "Americano",
        "glass": "collins",
        "method": "built",
        "garnish": "orange slice",
        "instructions": "Build over ice, top with soda.",
        "steps": [
            "Fill a collins glass with ice.",
            "Add {campari}.",
            "Add {sweet-vermouth}.",
            "Top with {soda-water}.",
            "Stir gently.",
            "Garnish with an orange slice.",
        ],
        "ingredients": [
            ("campari", "1 oz", False),
            ("sweet-vermouth", "1 oz", False),
            ("soda-water", "top", False),
        ],
    },
    {
        "id": "boulevardier",
        "name": "Boulevardier",
        "glass": "rocks",
        "method": "stirred",
        "garnish": "orange peel",
        "instructions": "Stir with ice, strain over a large cube.",
        "steps": [
            "Add {bourbon} to a mixing glass.",
            "Add {campari}.",
            "Add {sweet-vermouth}.",
            "Fill the mixing glass with ice.",
            "Stir for about 20 seconds, until cold.",
            "Strain into a rocks glass over one large ice cube.",
            "Express an orange peel over the top and drop it in.",
        ],
        "ingredients": [
            ("bourbon", "1 1/4 oz", False),
            ("campari", "1 oz", False),
            ("sweet-vermouth", "1 oz", False),
        ],
    },
    {
        "id": "paper-plane",
        "name": "Paper Plane",
        "glass": "coupe",
        "method": "shaken",
        "garnish": None,
        "instructions": "Equal parts. Shake with ice, strain into a chilled coupe.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {bourbon} to a shaker.",
            "Add {aperol}.",
            "Add {amaro-nonino}.",
            "Add {lemon-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Dump the ice water from the coupe.",
            "Strain into the chilled coupe.",
        ],
        "ingredients": [
            ("bourbon", "3/4 oz", False),
            ("aperol", "3/4 oz", False),
            ("amaro-nonino", "3/4 oz", False),
            ("lemon-juice", "3/4 oz", False),
        ],
    },
    {
        "id": "last-word",
        "name": "Last Word",
        "glass": "coupe",
        "method": "shaken",
        "garnish": "brandied cherry",
        "instructions": "Equal parts. Shake hard with ice, double-strain.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {gin} to a shaker.",
            "Add {green-chartreuse}.",
            "Add {maraschino}.",
            "Add {lime-juice}.",
            "Fill the shaker with ice.",
            "Shake hard for 10 to 12 seconds.",
            "Dump the ice water from the coupe.",
            "Double-strain into the chilled coupe.",
            "Garnish with a brandied cherry.",
        ],
        "ingredients": [
            ("gin", "3/4 oz", False),
            ("green-chartreuse", "3/4 oz", False),
            ("maraschino", "3/4 oz", False),
            ("lime-juice", "3/4 oz", False),
        ],
    },
    {
        "id": "sazerac",
        "name": "Sazerac",
        "glass": "rocks",
        "method": "stirred",
        "garnish": "lemon peel, discarded",
        "instructions": "Rinse a chilled glass with absinthe and discard. Stir everything else with ice and strain in, no ice.",
        "steps": [
            "Chill a rocks glass (fill it with ice water).",
            "Add {rich-syrup} to a mixing glass.",
            "Add {peychauds-bitters}.",
            "Add {rye-whiskey}.",
            "Fill the mixing glass with ice.",
            "Stir for about 30 seconds, until very cold.",
            "Empty the chilled glass.",
            "Add a small splash of {absinthe:name}, swirl to coat the glass, and pour out the extra.",
            "Strain the drink into the glass, with no ice.",
            "Express a lemon peel over the top, then discard it.",
        ],
        "ingredients": [
            ("rye-whiskey", "2 oz", False),
            ("rich-syrup", "1 tsp", False),
            ("peychauds-bitters", "3 dashes", False),
            ("absinthe", "rinse", True),
        ],
    },
    {
        "id": "vieux-carre",
        "name": "Vieux Carré",
        "glass": "rocks",
        "method": "stirred",
        "garnish": "lemon peel",
        "instructions": "Stir with ice, strain over fresh ice.",
        "steps": [
            "Add {rye-whiskey} to a mixing glass.",
            "Add {cognac}.",
            "Add {sweet-vermouth}.",
            "Add {benedictine}.",
            "Add {peychauds-bitters}.",
            "Add {aromatic-bitters}.",
            "Fill the mixing glass with ice.",
            "Stir for about 20 seconds, until cold.",
            "Fill a rocks glass with fresh ice.",
            "Strain the drink into the glass.",
            "Garnish with a lemon peel.",
        ],
        "ingredients": [
            ("rye-whiskey", "1 oz", False),
            ("cognac", "1 oz", False),
            ("sweet-vermouth", "1 oz", False),
            ("benedictine", "1 tsp", False),
            ("peychauds-bitters", "2 dashes", False),
            ("aromatic-bitters", "2 dashes", False),
        ],
    },
    {
        "id": "corpse-reviver-2",
        "name": "Corpse Reviver No. 2",
        "glass": "coupe",
        "method": "shaken",
        "garnish": "lemon peel",
        "instructions": "Rinse the glass with absinthe. Shake the rest with ice and strain in.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {gin} to a shaker.",
            "Add {triple-sec}.",
            "Add {lillet-blanc}.",
            "Add {lemon-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Empty the coupe, add a small splash of {absinthe:name}, swirl to coat, and pour out the extra.",
            "Strain the drink into the coupe.",
            "Garnish with a lemon peel.",
        ],
        "ingredients": [
            ("gin", "3/4 oz", False),
            ("triple-sec", "3/4 oz", False),
            ("lillet-blanc", "3/4 oz", False),
            ("lemon-juice", "3/4 oz", False),
            ("absinthe", "rinse", True),
        ],
    },
    {
        "id": "french-75",
        "name": "French 75",
        "glass": "flute",
        "method": "shaken",
        "garnish": "lemon twist",
        "instructions": "Shake gin, lemon and syrup with ice, strain into a flute, top with champagne.",
        "steps": [
            "Chill a champagne flute.",
            "Add {gin} to a shaker.",
            "Add {lemon-juice}.",
            "Add {simple-syrup}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into the chilled flute.",
            "Top slowly with {champagne}.",
            "Garnish with a lemon twist.",
        ],
        "ingredients": [
            ("gin", "1 oz", False),
            ("lemon-juice", "1/2 oz", False),
            ("simple-syrup", "1/2 oz", False),
            ("champagne", "top", False),
        ],
    },
    {
        "id": "espresso-martini",
        "name": "Espresso Martini",
        "glass": "coupe",
        "method": "shaken",
        "garnish": "three coffee beans",
        "instructions": "Shake very hard with ice (the foam is the whole point), then double-strain.",
        "steps": [
            "Chill a coupe (fill it with ice water) and pull a fresh shot of espresso.",
            "Add {vodka} to a shaker.",
            "Add {coffee-liqueur}.",
            "Add {coffee}.",
            "Fill the shaker with ice.",
            "Shake very hard for 15 seconds (the foam is the whole point).",
            "Dump the ice water from the coupe.",
            "Double-strain into the chilled coupe.",
            "Float three coffee beans on the foam.",
        ],
        "ingredients": [
            ("vodka", "2 oz", False),
            ("coffee-liqueur", "1/2 oz", False),
            ("coffee", "1 oz", False),
        ],
    },
    {
        "id": "white-russian",
        "name": "White Russian",
        "glass": "rocks",
        "method": "built",
        "garnish": None,
        "instructions": "Build vodka and coffee liqueur over ice, float the cream on top.",
        "steps": [
            "Fill a rocks glass with ice.",
            "Add {vodka}.",
            "Add {coffee-liqueur}.",
            "Stir briefly.",
            "Slowly pour {heavy-cream} over the back of a spoon so it floats on top.",
        ],
        "ingredients": [
            ("vodka", "2 oz", False),
            ("coffee-liqueur", "1 oz", False),
            ("heavy-cream", "1 oz", False),
        ],
    },
    {
        "id": "cosmopolitan",
        "name": "Cosmopolitan",
        "glass": "coupe",
        "method": "shaken",
        "garnish": "orange peel",
        "instructions": "Shake with ice, double-strain into a chilled coupe.",
        "steps": [
            "Chill a coupe (fill it with ice water while you mix).",
            "Add {vodka} to a shaker.",
            "Add {triple-sec}.",
            "Add {lime-juice}.",
            "Add {cranberry-juice}.",
            "Fill the shaker with ice.",
            "Shake hard for 10 seconds.",
            "Dump the ice water from the coupe.",
            "Double-strain into the chilled coupe.",
            "Express an orange peel over the top.",
        ],
        "ingredients": [
            ("vodka", "1 1/2 oz", False),
            ("triple-sec", "1/2 oz", False),
            ("lime-juice", "1/2 oz", False),
            ("cranberry-juice", "1 oz", False),
        ],
    },
    {
        "id": "mai-tai",
        "name": "Mai Tai",
        "glass": "rocks",
        "method": "shaken",
        "garnish": "mint sprig, spent lime shell",
        "instructions": "Shake with crushed ice, pour unstrained, mound more crushed ice on top.",
        "steps": [
            "Add {aged-rum} to a shaker.",
            "Add {curacao}.",
            "Add {orgeat}.",
            "Add {lime-juice}.",
            "Fill the shaker with crushed ice.",
            "Shake for 5 to 8 seconds.",
            "Pour everything, ice included, into a rocks glass.",
            "Mound more crushed ice on top.",
            "Garnish with a mint sprig and the spent lime shell.",
        ],
        "ingredients": [
            ("aged-rum", "2 oz", False),
            ("curacao", "1/2 oz", False),
            ("orgeat", "1/2 oz", False),
            ("lime-juice", "3/4 oz", False),
        ],
    },
    {
        "id": "pina-colada",
        "name": "Piña Colada",
        "glass": "hurricane",
        "method": "blended",
        "garnish": "pineapple wedge",
        "instructions": "Blend with a cup of crushed ice until smooth.",
        "steps": [
            "Add {white-rum} to a blender.",
            "Add {coconut-cream}.",
            "Add {pineapple-juice}.",
            "Add about 1 cup of crushed ice.",
            "Blend until smooth.",
            "Pour into a hurricane glass.",
            "Garnish with a pineapple wedge.",
        ],
        "ingredients": [
            ("white-rum", "2 oz", False),
            ("coconut-cream", "1 1/2 oz", False),
            ("pineapple-juice", "2 oz", False),
        ],
    },
    {
        "id": "caipirinha",
        "name": "Caipirinha",
        "glass": "rocks",
        "method": "built",
        "garnish": "lime wedge",
        "instructions": "Muddle lime with sugar in the glass, add cachaça and crushed ice, stir.",
        "steps": [
            "Cut half a lime into wedges and put them in a rocks glass (that's your {lime-juice}).",
            "Add {sugar}.",
            "Press the lime and sugar firmly with a muddler until the sugar dissolves.",
            "Fill the glass with crushed ice.",
            "Add {cachaca}.",
            "Stir well and serve with the lime still in it.",
        ],
        "ingredients": [
            ("cachaca", "2 oz", False),
            ("lime-juice", "3/4 oz", False),
            ("sugar", "2 tsp", False),
        ],
    },
    {
        "id": "gin-and-tonic",
        "name": "Gin & Tonic",
        "glass": "highball",
        "method": "built",
        "garnish": "lime wedge",
        "instructions": "Fill with ice, gin, then tonic poured down a barspoon.",
        "steps": [
            "Fill a highball glass with ice.",
            "Add {gin}.",
            "Add {tonic-water}, pouring slowly down a bar spoon to keep the bubbles.",
            "Garnish with a lime wedge.",
        ],
        "ingredients": [
            ("gin", "2 oz", False),
            ("tonic-water", "4 oz", False),
        ],
    },
    {
        "id": "tom-collins",
        "name": "Tom Collins",
        "glass": "collins",
        "method": "built",
        "garnish": "lemon wheel",
        "instructions": "Build over ice, top with soda, stir gently.",
        "steps": [
            "Add {gin} to a collins glass.",
            "Add {lemon-juice}.",
            "Add {simple-syrup}.",
            "Fill the glass with ice.",
            "Stir to mix.",
            "Top with {soda-water}.",
            "Stir gently once.",
            "Garnish with a lemon wheel.",
        ],
        "ingredients": [
            ("gin", "2 oz", False),
            ("lemon-juice", "1 oz", False),
            ("simple-syrup", "1/2 oz", False),
            ("soda-water", "top", False),
        ],
    },
    {
        "id": "mint-julep",
        "name": "Mint Julep",
        "glass": "julep cup",
        "method": "built",
        "garnish": "big mint bouquet",
        "instructions": "Press the mint into the syrup, add bourbon, fill with crushed ice and swizzle until the cup frosts.",
        "steps": [
            "Add {mint} to a julep cup.",
            "Add {rich-syrup}.",
            "Press the mint gently with a muddler.",
            "Add {bourbon}.",
            "Fill the cup with crushed ice.",
            "Swizzle (spin a bar spoon between your palms) until the outside of the cup frosts.",
            "Top with more crushed ice.",
            "Garnish with a big bouquet of mint.",
        ],
        "ingredients": [
            ("bourbon", "2 1/2 oz", False),
            ("rich-syrup", "1/2 oz", False),
            ("mint", "10 leaves", False),
        ],
    },
    {
        "id": "penicillin",
        "name": "Penicillin",
        "glass": "rocks",
        "method": "shaken",
        "garnish": "candied ginger",
        "instructions": "Shake the first four with ice, strain over a large cube, float the Islay scotch.",
        "steps": [
            "Add {scotch} to a shaker.",
            "Add {honey-syrup}.",
            "Add {lemon-juice}.",
            "Add {ginger-syrup}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a rocks glass over one large ice cube.",
            "Gently pour {islay-scotch} over the back of a spoon so it floats on top (if using).",
            "Garnish with candied ginger.",
        ],
        "ingredients": [
            ("scotch", "2 oz", False),
            ("honey-syrup", "3/4 oz", False),
            ("lemon-juice", "3/4 oz", False),
            ("ginger-syrup", "1/4 oz", False),
            ("islay-scotch", "1/4 oz float", True),
        ],
    },
]


def seed_recipes(conn) -> None:
    """Load the curated cocktails AND the curated shots (shot_data.py)."""
    from .recipe_store import seed_curated

    seed_curated(conn)
