"""The unique shots: hand-written, because no open dataset covers them."""

SHOTS = [
    {
        "id": "green-tea-shot",
        "name": "Green Tea Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Shake with ice, strain into a shot glass, top with a splash of lemon-lime soda.",
        "steps": [
            "Add {irish-whiskey} to a shaker.",
            "Add {peach-schnapps}.",
            "Add {sour-mix}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
            "Top with a splash of {lemon-lime-soda:name} (if using).",
        ],
        "ingredients": [
            ("irish-whiskey", "1/2 oz", False),
            ("peach-schnapps", "1/2 oz", False),
            ("sour-mix", "1/2 oz", False),
            ("lemon-lime-soda", "splash", True),
        ],
    },
    {
        "id": "white-tea-shot",
        "name": "White Tea Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "The Green Tea Shot with vodka instead of whiskey.",
        "steps": [
            "Add {vodka} to a shaker.",
            "Add {peach-schnapps}.",
            "Add {sour-mix}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
            "Top with a splash of {lemon-lime-soda:name} (if using).",
        ],
        "ingredients": [
            ("vodka", "1/2 oz", False),
            ("peach-schnapps", "1/2 oz", False),
            ("sour-mix", "1/2 oz", False),
            ("lemon-lime-soda", "splash", True),
        ],
    },
    {
        "id": "b-52",
        "name": "B-52",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Layer coffee liqueur, then Irish cream, then Grand Marnier.",
        "steps": [
            "Pour {coffee-liqueur} into a shot glass.",
            "Slowly pour {irish-cream} over the back of a bar spoon so it floats on top.",
            "Slowly pour {grand-marnier} over the spoon the same way, for a third layer.",
        ],
        "ingredients": [
            ("coffee-liqueur", "1/2 oz", False),
            ("irish-cream", "1/2 oz", False),
            ("grand-marnier", "1/2 oz", False),
        ],
    },
    {
        "id": "baby-guinness",
        "name": "Baby Guinness",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Coffee liqueur with a thin float of Irish cream, so it looks like a tiny pint.",
        "steps": [
            "Pour {coffee-liqueur} into a shot glass.",
            "Slowly pour {irish-cream} over the back of a bar spoon so it sits on top like a head of foam.",
        ],
        "ingredients": [
            ("coffee-liqueur", "1 oz", False),
            ("irish-cream", "1/4 oz", False),
        ],
    },
    {
        "id": "baby-beer",
        "name": "Baby Beer",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Licor 43 with a float of cream on top.",
        "steps": [
            "Pour {vanilla-liqueur} into a shot glass.",
            "Slowly pour {heavy-cream} over the back of a bar spoon so it floats on top.",
        ],
        "ingredients": [
            ("vanilla-liqueur", "1 oz", False),
            ("heavy-cream", "1/4 oz", False),
        ],
    },
    {
        "id": "lemon-drop-shot",
        "name": "Lemon Drop Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": "sugar rim",
        "instructions": "Shake with ice, strain into a sugar-rimmed shot glass.",
        "steps": [
            "Run a lemon wedge around the rim of a shot glass and dip it in sugar.",
            "Add {vodka} to a shaker.",
            "Add {triple-sec}.",
            "Add {lemon-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into the shot glass.",
        ],
        "ingredients": [
            ("vodka", "1 oz", False),
            ("triple-sec", "1/2 oz", False),
            ("lemon-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "kamikaze-shot",
        "name": "Kamikaze Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Equal parts vodka, triple sec and lime, shaken cold.",
        "steps": [
            "Add {vodka} to a shaker.",
            "Add {triple-sec}.",
            "Add {lime-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("vodka", "1/2 oz", False),
            ("triple-sec", "1/2 oz", False),
            ("lime-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "purple-hooter",
        "name": "Purple Hooter",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Vodka, raspberry liqueur and lime, shaken cold.",
        "steps": [
            "Add {vodka} to a shaker.",
            "Add {raspberry-liqueur}.",
            "Add {lime-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("vodka", "1/2 oz", False),
            ("raspberry-liqueur", "1/2 oz", False),
            ("lime-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "jager-bomb",
        "name": "Jäger Bomb",
        "glass": "shot",
        "method": "bomb",
        "garnish": None,
        "instructions": "Drop a shot of Jägermeister into a glass of energy drink.",
        "steps": [
            "Pour {energy-drink} into a rocks glass.",
            "Pour {jagermeister} into a sturdy shot glass.",
            "Drop the shot glass into the energy drink and drink it right away.",
        ],
        "ingredients": [
            ("jagermeister", "1 1/2 oz", False),
            ("energy-drink", "4 oz", False),
        ],
    },
    {
        "id": "vegas-bomb",
        "name": "Vegas Bomb",
        "glass": "shot",
        "method": "bomb",
        "garnish": None,
        "instructions": "Crown Royal, peach schnapps and cranberry, dropped into energy drink.",
        "steps": [
            "Pour {energy-drink} into a rocks glass.",
            "Add {canadian-whisky} to a shaker.",
            "Add {peach-schnapps}.",
            "Add {cranberry-juice}.",
            "Fill the shaker with ice and shake for 10 seconds.",
            "Strain into a sturdy shot glass.",
            "Drop the shot glass into the energy drink and drink it right away.",
        ],
        "ingredients": [
            ("canadian-whisky", "1/2 oz", False),
            ("peach-schnapps", "1/2 oz", False),
            ("cranberry-juice", "1/2 oz", False),
            ("energy-drink", "3 oz", False),
        ],
    },
    {
        "id": "irish-slammer",
        "name": "Irish Slammer",
        "glass": "shot",
        "method": "bomb",
        "garnish": None,
        "instructions": "Irish cream and Irish whiskey, dropped into half a pint of stout.",
        "steps": [
            "Pour {stout} into a pint glass and let it settle.",
            "Pour {irish-cream} into a sturdy shot glass.",
            "Slowly pour {irish-whiskey} over the back of a bar spoon so it floats on top.",
            "Drop the shot glass into the stout and drink it straight away, before the cream curdles.",
        ],
        "ingredients": [
            ("irish-cream", "1/2 oz", False),
            ("irish-whiskey", "1/2 oz", False),
            ("stout", "6 oz", False),
        ],
    },
    {
        "id": "sake-bomb",
        "name": "Sake Bomb",
        "glass": "shot",
        "method": "bomb",
        "garnish": None,
        "instructions": "A shot of sake balanced on chopsticks over beer, then knocked in.",
        "steps": [
            "Pour {lager} into a pint glass.",
            "Lay two chopsticks across the rim.",
            "Pour {sake} into a shot glass and balance it on the chopsticks.",
            "Bang the table so the shot drops in, then drink it right away.",
        ],
        "ingredients": [
            ("sake", "1 oz", False),
            ("lager", "6 oz", False),
        ],
    },
    {
        "id": "somaek",
        "name": "Somaek",
        "glass": "shot",
        "method": "bomb",
        "garnish": None,
        "instructions": "Korean soju and beer. Drop the soju in and give it one sharp stir.",
        "steps": [
            "Pour {lager} into a beer glass, about two-thirds full.",
            "Pour {soju} into a shot glass.",
            "Drop the shot glass in (or pour the soju in), then stir once with a chopstick so it fizzes up.",
            "Drink right away.",
        ],
        "ingredients": [
            ("soju", "1 1/2 oz", False),
            ("lager", "6 oz", False),
        ],
    },
    {
        "id": "boilermaker",
        "name": "Boilermaker",
        "glass": "shot",
        "method": "built",
        "garnish": None,
        "instructions": "A shot of whiskey with a beer chaser (or dropped in).",
        "steps": [
            "Pour {lager} into a pint glass.",
            "Pour {whiskey} into a shot glass.",
            "Drink the whiskey, then chase it with the beer (or drop the shot in).",
        ],
        "ingredients": [
            ("whiskey", "1 1/2 oz", False),
            ("lager", "8 oz", False),
        ],
    },
    {
        "id": "pickleback",
        "name": "Pickleback",
        "glass": "shot",
        "method": "built",
        "garnish": None,
        "instructions": "A shot of Irish whiskey chased with a shot of pickle brine.",
        "steps": [
            "Pour {irish-whiskey} into a shot glass.",
            "Pour {pickle-brine} into a second shot glass.",
            "Drink the whiskey, then the brine right after.",
        ],
        "ingredients": [
            ("irish-whiskey", "1 1/2 oz", False),
            ("pickle-brine", "1 oz", False),
        ],
    },
    {
        "id": "irish-breakfast-shot",
        "name": "Irish Breakfast Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Irish whiskey and butterscotch schnapps, with an orange juice chaser.",
        "steps": [
            "Pour {orange-juice} into a second shot glass for the chaser.",
            "Add {irish-whiskey} to a shaker.",
            "Add {butterscotch-schnapps}.",
            "Fill the shaker with ice and shake for 10 seconds.",
            "Strain into a shot glass.",
            "Drink the shot, then the orange juice.",
        ],
        "ingredients": [
            ("irish-whiskey", "1/2 oz", False),
            ("butterscotch-schnapps", "1/2 oz", False),
            ("orange-juice", "1 oz", False),
        ],
    },
    {
        "id": "tequila-slammer",
        "name": "Tequila Slammer",
        "glass": "shot",
        "method": "built",
        "garnish": None,
        "instructions": "Tequila and soda, covered, slammed, drunk while it fizzes.",
        "steps": [
            "Pour {blanco-tequila} into a sturdy rocks glass.",
            "Add {lemon-lime-soda}.",
            "Cover the glass with your palm and bring it down firmly on the table once.",
            "Drink it in one go while it's still fizzing.",
        ],
        "ingredients": [
            ("blanco-tequila", "1 oz", False),
            ("lemon-lime-soda", "1 oz", False),
        ],
    },
    {
        "id": "mind-eraser",
        "name": "Mind Eraser",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Coffee liqueur, vodka and soda in layers, drunk fast through a straw.",
        "steps": [
            "Fill a small rocks glass with ice.",
            "Pour in {coffee-liqueur}.",
            "Slowly pour {vodka} over the back of a bar spoon so it floats on top.",
            "Top with {soda-water:name}.",
            "Drink it all at once through a straw.",
        ],
        "ingredients": [
            ("coffee-liqueur", "1 oz", False),
            ("vodka", "1 oz", False),
            ("soda-water", "top", False),
        ],
    },
    {
        "id": "buttery-nipple",
        "name": "Buttery Nipple",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Butterscotch schnapps with Irish cream floated on top.",
        "steps": [
            "Pour {butterscotch-schnapps} into a shot glass.",
            "Slowly pour {irish-cream} over the back of a bar spoon so it floats on top.",
        ],
        "ingredients": [
            ("butterscotch-schnapps", "1 oz", False),
            ("irish-cream", "1/2 oz", False),
        ],
    },
    {
        "id": "slippery-nipple",
        "name": "Slippery Nipple",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Sambuca with Irish cream floated on top.",
        "steps": [
            "Pour {sambuca} into a shot glass.",
            "Slowly pour {irish-cream} over the back of a bar spoon so it floats on top.",
            "Add a drop of {grenadine:name} to the middle (if using).",
        ],
        "ingredients": [
            ("sambuca", "1 oz", False),
            ("irish-cream", "1/2 oz", False),
            ("grenadine", "1 drop", True),
        ],
    },
    {
        "id": "brain-hemorrhage",
        "name": "Brain Hemorrhage",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Peach schnapps, a slow drizzle of Irish cream, then grenadine. It's meant to look gross.",
        "steps": [
            "Pour {peach-schnapps} into a shot glass.",
            "Drizzle {irish-cream} in slowly. It curdles into little clumps, which is the point.",
            "Add {grenadine} a few drops at a time so it sinks through the cream.",
        ],
        "ingredients": [
            ("peach-schnapps", "1 oz", False),
            ("irish-cream", "1/4 oz", False),
            ("grenadine", "1 tsp", False),
        ],
    },
    {
        "id": "irish-flag",
        "name": "Irish Flag",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Green, white and orange layers: crème de menthe, Irish cream, Grand Marnier.",
        "steps": [
            "Pour {green-creme-de-menthe} into a shot glass.",
            "Slowly pour {irish-cream} over the back of a bar spoon so it floats on top.",
            "Slowly pour {grand-marnier} over the spoon the same way, for a third layer.",
        ],
        "ingredients": [
            ("green-creme-de-menthe", "1/2 oz", False),
            ("irish-cream", "1/2 oz", False),
            ("grand-marnier", "1/2 oz", False),
        ],
    },
    {
        "id": "washington-apple-shot",
        "name": "Washington Apple Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Crown Royal, sour apple schnapps and cranberry, shaken cold.",
        "steps": [
            "Add {canadian-whisky} to a shaker.",
            "Add {sour-apple-schnapps}.",
            "Add {cranberry-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("canadian-whisky", "1/2 oz", False),
            ("sour-apple-schnapps", "1/2 oz", False),
            ("cranberry-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "jolly-rancher-shot",
        "name": "Jolly Rancher Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Peach schnapps, sour apple schnapps and cranberry.",
        "steps": [
            "Add {peach-schnapps} to a shaker.",
            "Add {sour-apple-schnapps}.",
            "Add {cranberry-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("peach-schnapps", "1/2 oz", False),
            ("sour-apple-schnapps", "1/2 oz", False),
            ("cranberry-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "scooby-snack",
        "name": "Scooby Snack",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Melon liqueur, coconut rum, pineapple and a splash of cream.",
        "steps": [
            "Add {melon-liqueur} to a shaker.",
            "Add {coconut-rum}.",
            "Add {pineapple-juice}.",
            "Add {heavy-cream}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("melon-liqueur", "1/2 oz", False),
            ("coconut-rum", "1/2 oz", False),
            ("pineapple-juice", "1/2 oz", False),
            ("heavy-cream", "splash", False),
        ],
    },
    {
        "id": "surfer-on-acid",
        "name": "Surfer on Acid",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Jägermeister, coconut rum and pineapple juice.",
        "steps": [
            "Add {jagermeister} to a shaker.",
            "Add {coconut-rum}.",
            "Add {pineapple-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("jagermeister", "1/2 oz", False),
            ("coconut-rum", "1/2 oz", False),
            ("pineapple-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "gummy-bear-shot",
        "name": "Gummy Bear Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Raspberry vodka, peach schnapps and pineapple, topped with a splash of Sprite.",
        "steps": [
            "Add {raspberry-vodka} to a shaker.",
            "Add {peach-schnapps}.",
            "Add {pineapple-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
            "Top with a splash of {lemon-lime-soda:name} (if using).",
        ],
        "ingredients": [
            ("raspberry-vodka", "1/2 oz", False),
            ("peach-schnapps", "1/2 oz", False),
            ("pineapple-juice", "1/2 oz", False),
            ("lemon-lime-soda", "splash", True),
        ],
    },
    {
        "id": "pineapple-upside-down-shot",
        "name": "Pineapple Upside-Down Cake Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Vanilla vodka and pineapple, with grenadine sunk to the bottom.",
        "steps": [
            "Add {vanilla-vodka} to a shaker.",
            "Add {pineapple-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
            "Add {grenadine} slowly so it sinks to the bottom.",
        ],
        "ingredients": [
            ("vanilla-vodka", "3/4 oz", False),
            ("pineapple-juice", "3/4 oz", False),
            ("grenadine", "1 tsp", False),
        ],
    },
    {
        "id": "apple-pie-shot",
        "name": "Apple Pie Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": "cinnamon sugar rim",
        "instructions": "Vanilla vodka and apple juice in a cinnamon-sugar rimmed glass.",
        "steps": [
            "Run a lemon wedge around the rim of a shot glass and dip it in cinnamon sugar (or plain sugar).",
            "Add {vanilla-vodka} to a shaker.",
            "Add {apple-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into the shot glass.",
        ],
        "ingredients": [
            ("vanilla-vodka", "3/4 oz", False),
            ("apple-juice", "3/4 oz", False),
        ],
    },
    {
        "id": "cinnamon-toast-crunch",
        "name": "Cinnamon Toast Crunch",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "RumChata and Fireball, shaken cold. Tastes like the cereal milk.",
        "steps": [
            "Add {rumchata} to a shaker.",
            "Add {cinnamon-whiskey}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("rumchata", "3/4 oz", False),
            ("cinnamon-whiskey", "3/4 oz", False),
        ],
    },
    {
        "id": "oatmeal-cookie",
        "name": "Oatmeal Cookie",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Irish cream, butterscotch schnapps and a little cinnamon schnapps.",
        "steps": [
            "Add {irish-cream} to a shaker.",
            "Add {butterscotch-schnapps}.",
            "Add {cinnamon-schnapps}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("irish-cream", "1/2 oz", False),
            ("butterscotch-schnapps", "1/2 oz", False),
            ("cinnamon-schnapps", "1/4 oz", False),
        ],
    },
    {
        "id": "chocolate-cake-shot",
        "name": "Chocolate Cake Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": "sugared lemon wedge",
        "instructions": "Citrus vodka and Frangelico. Bite a sugared lemon wedge after. It really does taste like cake.",
        "steps": [
            "Dip a lemon wedge in sugar and set it aside.",
            "Add {citrus-vodka} to a shaker.",
            "Add {hazelnut-liqueur}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
            "Drink the shot, then bite the sugared lemon wedge.",
        ],
        "ingredients": [
            ("citrus-vodka", "3/4 oz", False),
            ("hazelnut-liqueur", "3/4 oz", False),
        ],
    },
    {
        "id": "peppermint-patty-shot",
        "name": "Peppermint Patty Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Peppermint schnapps and dark crème de cacao, shaken cold.",
        "steps": [
            "Add {peppermint-schnapps} to a shaker.",
            "Add {dark-creme-de-cacao}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("peppermint-schnapps", "3/4 oz", False),
            ("dark-creme-de-cacao", "3/4 oz", False),
        ],
    },
    {
        "id": "alabama-slammer-shot",
        "name": "Alabama Slammer Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Southern Comfort, amaretto, sloe gin and orange juice.",
        "steps": [
            "Add {southern-comfort} to a shaker.",
            "Add {amaretto}.",
            "Add {sloe-gin}.",
            "Add {orange-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("southern-comfort", "1/2 oz", False),
            ("amaretto", "1/2 oz", False),
            ("sloe-gin", "1/4 oz", False),
            ("orange-juice", "1/2 oz", False),
        ],
    },
    {
        "id": "three-wise-men",
        "name": "Three Wise Men",
        "glass": "shot",
        "method": "built",
        "garnish": None,
        "instructions": "Bourbon, Tennessee whiskey and Scotch in one glass. Jim, Jack and Johnnie.",
        "steps": [
            "Pour {bourbon} into a shot glass.",
            "Add {tennessee-whiskey}.",
            "Add {scotch}.",
        ],
        "ingredients": [
            ("bourbon", "1/2 oz", False),
            ("tennessee-whiskey", "1/2 oz", False),
            ("scotch", "1/2 oz", False),
        ],
    },
    {
        "id": "four-horsemen",
        "name": "Four Horsemen",
        "glass": "shot",
        "method": "built",
        "garnish": None,
        "instructions": "Three Wise Men plus tequila. Use a double shot glass.",
        "steps": [
            "Pour {bourbon} into a double shot glass.",
            "Add {tennessee-whiskey}.",
            "Add {scotch}.",
            "Add {tequila}.",
        ],
        "ingredients": [
            ("bourbon", "1/2 oz", False),
            ("tennessee-whiskey", "1/2 oz", False),
            ("scotch", "1/2 oz", False),
            ("tequila", "1/2 oz", False),
        ],
    },
    {
        "id": "tequila-salt-lime",
        "name": "Tequila, Salt & Lime",
        "glass": "shot",
        "method": "built",
        "garnish": "lime wedge, salt",
        "instructions": "The classic tequila shot: lick the salt, shoot, bite the lime.",
        "steps": [
            "Pour {blanco-tequila} into a shot glass.",
            "Put {salt} on the back of your hand and have a lime wedge ready.",
            "Lick the salt, drink the shot, then bite the lime.",
        ],
        "ingredients": [
            ("blanco-tequila", "1 1/2 oz", False),
            ("salt", "pinch", False),
        ],
    },
    {
        "id": "fireball-apple-shot",
        "name": "Fireball Apple Shot",
        "glass": "shot",
        "method": "shaken",
        "garnish": None,
        "instructions": "Cinnamon whisky and apple juice. Apple pie, faster.",
        "steps": [
            "Add {cinnamon-whiskey} to a shaker.",
            "Add {apple-juice}.",
            "Fill the shaker with ice.",
            "Shake for 10 seconds.",
            "Strain into a shot glass.",
        ],
        "ingredients": [
            ("cinnamon-whiskey", "3/4 oz", False),
            ("apple-juice", "3/4 oz", False),
        ],
    },
    {
        "id": "banana-split-shot",
        "name": "Banana Split Shot",
        "glass": "shot",
        "method": "layered",
        "garnish": None,
        "instructions": "Dark crème de cacao, banana rum, then a float of cream.",
        "steps": [
            "Pour {dark-creme-de-cacao} into a shot glass.",
            "Slowly pour {banana-rum} over the back of a bar spoon so it floats on top.",
            "Slowly pour {heavy-cream} over the spoon the same way, for a third layer.",
        ],
        "ingredients": [
            ("dark-creme-de-cacao", "1/2 oz", False),
            ("banana-rum", "1/2 oz", False),
            ("heavy-cream", "1/4 oz", False),
        ],
    },
]
